### ISSUE TITLE
Not working with Laravel 7+

### ISSUE THREAD

**Issue by mprince2k18** [prodeveloper/social-share#52] opened 2020-07-12 18:33 UTC
This package is not updated for Laravel 7+, but working with 6.

**Comment by mprince2k18** [comment] 2020-07-12 18:34
This package is not updated for Laravel 7+, but working with 6.

**Comment by lsmith77** [comment] 2020-08-12 09:54
the issue is that the 5.5.0 tag was not pushed to packagist.org .. I guess use dev-master instead

**Comment by atiehmokhtari** [comment] 2020-08-18 09:34
I also have this issue and using dev-master did not solve the issue. now my website is not working for the pages I have used this package
what is the solution ?

**Comment by nafplann** [comment] 2020-08-23 18:25
fixed with: composer require chencha/share:dev-master

**Comment by datashaman** [comment] 2021-12-23 04:31
This is resolved in the latest release, which is also available on packagist.

**Closed as completed by datashaman** 2021-12-23 04:31 UTC
